// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roterizador.Persistence;

namespace Roterizador.EntityPostgres.Migrations
{
    [DbContext(typeof(RoterizadorContext))]
    partial class RoterizadorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Roterizador.Domain.Model.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_COORDINATE")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ROT_COORDINATES");
                });

            modelBuilder.Entity("Roterizador.Domain.Model.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ROUTE")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EndId")
                        .HasColumnType("integer");

                    b.Property<int?>("StartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndId");

                    b.HasIndex("StartId");

                    b.ToTable("ROT_ROUTES");
                });

            modelBuilder.Entity("Roterizador.Domain.Model.Route", b =>
                {
                    b.HasOne("Roterizador.Domain.Model.Coordinate", "End")
                        .WithMany()
                        .HasForeignKey("EndId");

                    b.HasOne("Roterizador.Domain.Model.Coordinate", "Start")
                        .WithMany()
                        .HasForeignKey("StartId");
                });
#pragma warning restore 612, 618
        }
    }
}
